export const REASON_MASTER_TABLE_DATA_FETCH_START =
  "REASON_MASTER_TABLE_DATA_FETCH_START";
  export const REASON_MASTER_TABLE_DATA_FETCH_SUCCESS =
  "REASON_MASTER_TABLE_DATA_FETCH_SUCCESS";
export const REASON_MASTER_TABLE_DATA_FETCH_FAILED =
  "REASON_MASTER_TABLE_DATA_FETCH_FAILED";
  export const REASON_MASTER_CREATE_START = "REASON_MASTER_CREATE_START";
export const REASON_MASTER_CREATE_SUCCESS = "REASON_MASTER_CREATE_SUCCESS";
export const REASON_MASTER_CREATE_FAILED = "REASON_MASTER_CREATE_SUCCESS";
export const REASON_MASTER_UPDATE_START = "REASON_MASTER_UPDATE_START";
export const REASON_MASTER_UPDATE_SUCCESS = "REASON_MASTER_UPDATE_SUCCESS";
export const REASON_MASTER_UPDATE_FAILED = "REASON_MASTER_UPDATE_SUCCESS";